index:
    path: /
    controller: App\Controller\OverviewController::indexAction

register:
    path: /register
    controller: App\Controller\SecurityController::registerAction

login:
    path: /login
    controller: App\Controller\SecurityController::loginAction
password:
    path: /password
    controller: App\Controller\SecurityController::forgotPasswordAction
