feed:
    path: /feed
    controller: App\Controller\OverviewController::indexAction

register:
    path: /register
    controller: App\Controller\SecurityController::registerAction

login:
    path: /login
    controller: App\Controller\SecurityController::loginAction

password:
    path: /password
    controller: App\Controller\SecurityController::forgotPasswordAction
    
feed:
    path: /feed
    controller: App\Controller\FeedController::indexAction

comment:
    path: /comment
    controller: App\Controller\CommentController::createAction

entry:
    path: /entry
    controller: App\Controller\FeedController::createAction